### PR TITLE
Fix ViewHelpers.owner?/2 bug

### LINKED ISSUE #271: ViewHelper.owner?/2 broken for Waiver
https://app.honeybadger.io/projects/49977/faults/33279565

ViewHelper.owner?/2 broken for Waiver, no matching function clause.

### PR DESCRIPTION
**Pull request by axelclark**
* Function clause doesnt match for Waiver in Waiver index
* Closes #271

### CODE REVIEW

File: web/views/view_helpers.ex [hunk 1]
```diff
@@ -6,19 +6,19 @@ defmodule Ex338.ViewHelpers do
     Enum.map(players, &(format_select(&1)))
   end
 
-  def owner?(%User{id: id}, %FantasyTeam{owners: owners}) do
+  def owner?(%User{id: current_user_id}, %FantasyTeam{owners: owners}) do
     owners
-    |> Enum.any?(&(&1.user_id == id))
+    |> Enum.any?(&(&1.user_id == current_user_id))
```
Comment (axelclark) [inline web/views/view_helpers.ex]: Use a function call when a pipeline is only one function long

**Comment by axelclark** [comment]
Ebert has finished reviewing this Pull Request and has found:

* 1 possible new issue (including those that may have been commented here).
* 1 fixed issue! 🎉

You can see more details about this review at https://ebertapp.io/github/axelclark/ex338/pulls/272.

**Comment by axelclark** [comment]
Ebert has finished reviewing this Pull Request and has found:

* 1 fixed issue! 🎉

You can see more details about this review at https://ebertapp.io/github/axelclark/ex338/pulls/272.
