### PR TITLE
Wallaby

### LINKED ISSUE #253: Wallaby tests need to be fixed
Not working properly after switch to Ecto 2.1.  Also need major update to use Wallaby 0.16.0

### PR DESCRIPTION
**Pull request by axelclark**
Update Wallaby Integration tests
  
* Updated version to 0.16.1  
* Updated to use new DSL with 0.16.1
* Removed create test that were duplicates
* Closes #253

### CODE REVIEW

File: test/support/acceptance_case.ex [hunk 1]
```diff
@@ -5,18 +5,23 @@ defmodule Ex338.AcceptanceCase do
     quote do
       use Wallaby.DSL
 
-      import Ecto.Schema
-      import Ecto.Query, only: [from: 2]
-      import Ex338.Router.Helpers
+      alias Ex338.Repo
+      import Ecto
+      import Ecto.Changeset
+      import Ecto.Query
```
Comment (axelclark) [inline test/support/acceptance_case.ex]: Most of the time you are using the multi-alias/require/import/use syntax, but here you are using multiple single directives

**Comment by axelclark** [comment]
Ebert has finished reviewing this Pull Request and has found:

* 1 possible new issue (including those that may have been commented here).

You can see more details about this review at https://ebertapp.io/github/axelclark/ex338/pulls/255.
