### PR TITLE
Remove admin & owner duplicate email addresses

### LINKED ISSUE #235: A League Waiver Emails Not Sent
Feb 07 09:52:56 the338challenge app/web.1:  17:52:56.093 request_id=7b38db84-2241-4f94-9cd3-f69a224de9d8 [error] Email failed to send 

The A league waiver emails are not being sent by the application.  The app is returning an error.

### PR DESCRIPTION
**Pull request by axelclark**
* SendGrid now errors if there are duplicate email addresses
* Update email to ensure all recipients are unique
* Improve error messages for emails
* Log the error reason when there is an erro in the notification email
* Closes #235

### CODE REVIEW

File: web/emails/notification_email.ex [hunk 1]
```diff
@@ -4,10 +4,11 @@ defmodule Ex338.NotificationEmail do
   require Logger
   alias Ex338.{Waiver, Repo, Owner, User, Mailer}
 
-  def draft_update(conn, league, last_picks, next_picks, recipients, admins) do
+  def draft_update(conn, league, last_picks, next_picks, owners, admins) do
```
Comment (credoci) [inline web/emails/notification_email.ex]: Function takes too many parameters (arity is 6, max is 5).

**Comment by axelclark** [comment]
Ebert has finished reviewing this Pull Request and has found:

* 2 fixed issues! 🎉

You can see more details about this review at https://ebertapp.io/github/axelclark/ex338/pulls/236.
