### PR TITLE
Minor Fixes and Add Validations

### LINKED ISSUE #363: Compiler Warnings 20171125
remote: warning: unused alias FantasyPlayer
remote:   lib/ex338/fantasy_player.ex:6
remote: 
remote: warning: unused alias Repo
remote:   lib/ex338/fantasy_player.ex:6

### LINKED ISSUE #367: Add validate inclusion for options in schemas
See: https://hexdocs.pm/ecto/Ecto.Changeset.html#validate_inclusion/4

For example can validate Trade status is one of ["Pending", "Approved", "Disapproved"]

### PR DESCRIPTION
**Pull request by axelclark**
* Remove unused aliases from FantasyPlayer
* Closes #363
* Validates string is one of the options listed in module
* Closes #367

### CODE REVIEW

File: test/ex338/trade_test.exs [hunk 1]
```diff
@@ -3,26 +3,43 @@ defmodule Ex338.TradeTest do
...
+     assert changeset.valid?
+   end
+
+   @invalid_attrs %{}
+   test "invalid without assoc to cast" do
+     changeset = Trade.new_changeset(%Trade{}, @invalid_attrs)
+     refute changeset.valid?
+   end
+
+
```
Comment (axelclark) [inline test/ex338/trade_test.exs]: There should be no more than 1 consecutive blank lines.

**Comment by axelclark** [comment]
Ebert has finished reviewing this Pull Request and has found:

* 4 possible new issues (including those that may have been commented here).

You can see more details about this review at https://ebertapp.io/github/axelclark/ex338/pulls/368.
